#import gzip
import zopfli.gzip as zgzip 
import re
import sys
import os

def extreme_minify(text):
    # 1. Сначала схлопываем всё в одну строку (уже было)
    text = " ".join(line.strip() for line in text.splitlines() if line.strip())
    # 2. Убираем пробелы вокруг операторов и скобок
    # Список символов, вокруг которых пробелы не нужны
    chars = [r'\(', r'\)', r'\{', r'\}', r'\[', r'\]', r',', r';', r':', r'=', r'>', r'<', r'\+', r'\-']
    for char in chars:
        # Убираем пробелы ДО и ПОСЛЕ символа
        text = re.sub(r'\s*' + char + r'\s*', char.replace('\\', ''), text)
    # 3. Убираем множественные пробелы, если остались
    text = re.sub(r'\s+', ' ', text)
    return text.strip()

def process_smart_folding(text, is_extreme, fold_level):
    if is_extreme:
        return extreme_minify(text)

    # РЕЖИМ --hard N (Свертка с заменой на пробелы)
    parts = re.split(r'(<(?:style|script).*?>|</(?:style|script)>)', text, flags=re.IGNORECASE)
    final_output = []
    current_depth = 0
    in_special_block = False

    for part in parts:
        if not part.strip(): continue
        if re.match(r'<(style|script)', part, re.IGNORECASE):
            in_special_block = True
            final_output.append("\n" + part.strip())
            continue
        if re.match(r'</(style|script)', part, re.IGNORECASE):
            in_special_block = False
            final_output.append("\n" + part.strip())
            continue

        if in_special_block:
            for line in part.splitlines():
                line = line.strip()
                if not line: continue
                open_b, close_b = line.count('{'), line.count('}')
                # Если глубже уровня - заменяем \n на пробел, иначе - на \n
                final_output.append((" " if current_depth >= fold_level else "\n") + line)
                current_depth += (open_b - close_b)
        else:
            # HTML логика (уровень 0 в HTML - все в строку через пробел)
            tags = re.split(r'(<[^>]+>)', part)
            for tag in tags:
                tag = tag.strip()
                if not tag: continue
                if fold_level > 0 and re.match(r'<(/?(?:head|body|div|h\d|section|table|script|style))', tag, re.IGNORECASE):
                    final_output.append("\n" + tag)
                else:
                    final_output.append(" " + tag)

    return "".join(final_output).strip()

def main():
    if len(sys.argv) < 2:
        print("Использование: python3 hzipper.py <file> [--hard] [N]")
        return

    input_path = sys.argv[1]
    is_hard = "--hard" in sys.argv

    # Определяем: задано ли число N после --hard
    is_extreme = is_hard # По умолчанию считаем экстремальным, если есть --hard
    fold_level = 0
    for arg in sys.argv[2:]:
        if arg.isdigit():
            fold_level = int(arg)
            is_extreme = False # Если есть число, это уже не экстремальный режим
            break

    with open(input_path, "r", encoding="utf-8") as f:
        full_text = f.read()
        raw_size = len(full_text)
    # Захват префикса и контента
    prefix_match = re.search(r'^(.*?R"=====\()', full_text, re.DOTALL)
    if prefix_match:
        prefix = prefix_match.group(1)
        content = full_text[full_text.find('R"=====(')+8 : full_text.rfind(')=====";')]
    else:
        prefix = f'const uint8_t {os.path.basename(input_path).split(".")[0].upper()}[] PROGMEM = {{'
        content = full_text

    # Чистка комментариев
    content = re.sub(r'/\*.*?\*/', '', content, flags=re.DOTALL)
    content = re.sub(r'(?<!:)//.*', '', content)

    # Обработка
    if is_hard:
        content = process_smart_folding(content, is_extreme, fold_level)
    else:
        content = "\n".join(l.rstrip() for l in content.splitlines() if l.strip())

    with open("debug_minified.html", "w", encoding="utf-8") as f:
        f.write(content)

    #compressed = gzip.compress(content.encode("utf-8"), compresslevel=9)
    compressed = zgzip.compress(content.encode("utf-8"))

    var_match = re.search(r'(?:char|uint8_t)\s+([\w\d_]+)\[\]', prefix)
    var_name = var_match.group(1) if var_match else "INDEX_HTML"

    out_h = input_path.replace(".h", "") + "_gzip.h"
    # Собираем команду из аргументов sys.argv
    command_line = " ".join(sys.argv)

    with open(out_h, "w") as f:
        # Записываем комментарий с командой вызова
        f.write(f"// Generated by: python3 {command_line}\n")
        f.write(f"// Mode: {'EXTREME' if is_extreme else 'Hard L'+str(fold_level) if is_hard else 'Lite'}\n")
        f.write(f"const uint8_t {var_name}[] PROGMEM = {{\n  ")
        for i, b in enumerate(compressed):
            # Пишем байт, а затем запятую, если это не последний элемент (i < len - 1)
            f.write(f"0x{b:02x}" + (", " if i < len(compressed) - 1 else ""))
            # Перенос строки каждые 16 байт, но только если это не самый конец
            if (i + 1) % 16 == 0 and i < len(compressed) - 1:
                f.write("\n  ")
        f.write(f"\n}};\nconst uint32_t {var_name}_LEN = {len(compressed)};\n")

    print(f"Done! Mode: {'EXTREME' if is_extreme else 'Folding L'+str(fold_level)}")
    print(f"--- Size ---")
    print(f"Original (Disk): {os.path.getsize(input_path)} bytes") 
    print(f"Processed (no LF):   {raw_size} bytes")
    print(f"Minified (Debug): {len(content.encode('utf-8'))} bytes")
    print(f"Final GZIP:       {len(compressed)} bytes")

if __name__ == "__main__":
    main()
